imports:
    - { resource: config.yml }

doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
parameters:
    image_directory: '%kernel.root_dir%/../web/images'
    allowed_mime_types: [image/jpeg, image/png]
    allowed_file_size: 7000000 # file size in bytes
